### ISSUE TITLE
Add API to instantiate a class later: when the hook is fired

### ISSUE THREAD

**Issue by szepeviktor** [widoz/wp-hooks#13]
```php
// Example usage
addActionOnceLater('init', ['ClassToInstantiate', 'hookMethod'], 10, 2);

// in Factory
$hook = function () use ($hookClass, $hookMethod) {
    ($hookMethod === null) ? new $hookClass() : (new $hookClass())->$hookMethod;
}
```

What do you think?

**Comment by szepeviktor** [comment]
`$hookMethod === ''` is the usual poorly written WordPress "class" with add_action()-s in it constructor.

**Comment by widoz** [comment]
What about the following one?

```
$instance = new MyClass();
add_action('init', function() use ($instance) {
    addActionOnce('action_name', [$intance, 'myMethod']);
});
```

It has the advantage that you can reuse the same instance of a class and hook different methods to different actions.

Think that for every action you have to create a new instance which is unnecessary memory consuming.

Thoughts?

**Comment by szepeviktor** [comment]
Thank you for your answer.

You are **too normal**!!

Many-many-many WordPress classes are few `add_action`-s in constructor + the hooked (mainly `static`) functions thus it is *not* something we may call an object.

So it is **impossible** to instantiate them as it would result in adding hooks.

Could you please support this anti-pattern with `addActionOnceLater()`?

**Comment by szepeviktor** [comment]
BTW I so not write this kind of code.

**Comment by widoz** [comment]
I think instantiate classes and manage dependencies is outside the scope of this package plus, creating instances and hold them should be concern of a Container.

Probably I misunderstanding but what exactly should be the code of `addActionOnceLater`?

**Comment by szepeviktor** [comment]
`addActionOnceLater`: To take the burden of instantiation.

More than 90% of the - so called - "classes" are not objects in the WordPress ecosystem but a list of functions with add_action in the constructor/an "init" method.

I do understand you do not want that number to grow.

I've just released two classes doing just that as I work with sub-junior - so called - "developers" https://github.com/szepeviktor/Toolkit4WP/tree/master/src

**Comment by widoz** [comment]
Sorry but I do not like that way because of some points I'll list below but first of all I want to clarify that a class constructor should not do anything else then set it's own properties.
Any other action can be considered as a side-effect. 

There's a convension to have a method `init` which set all of the hooks the class will take care of, but most of the time that produce a class which is just a container for methods hooked to some WordPress hook that does not have any correlation each other. Consider to use functions instead. 

That's break the SRP (Single Responsible Principle). 

We should lean to solutions which are framework indipendent as much as possible to make our code interoperable and stop to reinvent the wheel every time. 

That's are the main reasons why I do not like the WordPress way even if that is a common pattern.

**Comment by szepeviktor** [comment]
Okay-okay, I do understand all that.

I work with big number of WordPress-way developers and - I think - I cannot make them think your way.
