### ISSUE TITLE
No lock file

### ISSUE THREAD

**Issue by szepeviktor** [widoz/wp-hooks#20]
Please remove composer.lock file as we are a library.

**Comment by widoz** [comment]
Could you kindly explain why? Not sure to understand the full implications.

I imagine that's because the consumer of this module could want to install other versions of the dependencies but that isn't managed by composer it self despite the fact that this module include the `composer.lock`?

**Comment by szepeviktor** [comment]
> I imagine that's because the consumer of this module could want to install other versions of the dependencies

Actually Composer does not take lock file into account when wp-hooks is a dependency.
That is why.

**Comment by widoz** [comment]
Thanks for the info. 

But if we take it, that will be useful during development because everyone which is involved in the project will get the same dependencies versions and the development will go linear and will solve the "it works on my machine" problem. 

Btw I'll do more research about this to collect pros and cons, if you have some please share it.

**Comment by szepeviktor** [comment]
> that will be useful during development because everyone which is involved in the project will get the same dependencies versions

Yes!

**Comment by widoz** [comment]
In this case I'll keep it.
