### ISSUE TITLE
Ultra-compressed hooking

### ISSUE THREAD

**Issue by szepeviktor** [widoz/wp-hooks#6]
Recently I wrote a tool to hook constructors like this

`HookConstructorTo::init(MyClass::class, 0);`

It hooks MyClass' constructor to the `init` action at priority zero.

https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wordpress/_core-hook-constructor-to.php#L13

What do you think?

**Comment by widoz** [comment]
That will prevent you to reuse code, thinking in terms of Services and tasks there are classes which can be reused and in this sense you cannot pass everything to a constructor just because you want to use that value within the class, there are services which are better to inject and there are values which need to be passed to methods of a class because them are concerns of a specific task.

A part that I see some problems like, how do you remove a filter if you need? Not all classes has a constructor but they can perform a task anyhow.

I usually split in phases of my application defining Containers, Service Provider and then Bootstrap the application something that cannot be accomplished with your solution.

Let's say I want to have a service which oper on a `WP_Post` if you pass it to the constructor as dependency your instance can work only with that post type and: 1 you have to create a new instance every time you want to perform action on a post, 2 you cannot take advantage of code reuse because you cannot inject the instance of that class into another class which can reuse the logic to perform some other tasks.

But more problematic is that, you'll create a new instance of that class you have in your filter callback everytime the filter callback is executed which waste memory without adding benefit.

If you want to lazy load classes only when and if them are needed I would suggest you to take an eye on Containers solution https://www.php-fig.org/psr/psr-11/ and for implementation https://github.com/mnapoli/simplex , there are obvious other implementation out there.

Regarding service providers https://github.com/container-interop/service-provider then you can add some class on top of that which bootstrap your modules where you could add filters and actions.

That's basically what I know and what works most if you want to have a clean design, separate concerns and make your code reusable.

**Comment by szepeviktor** [comment]
I see you are a developer with normal attitude.
But 99.99% of classes in the WordPress ecosystem put `add_action` and `add_filter` in the constructor: making is not an OOP object but a bunch of methods :(
